version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: swapi-db
    environment:
      - POSTGRES_USER=swapi
      - POSTGRES_PASSWORD=swapi_pass
      - POSTGRES_DB=swapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - swapi-network

networks:
  swapi-network:
    driver: bridge

volumes:
  postgres_data:
