apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapi-backend
  labels:
    app: swapi
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swapi
      tier: backend
  template:
    metadata:
      labels:
        app: swapi
        tier: backend
    spec:
      containers:
      - name: backend
        image: whis-19/swapi-backend:latest
        ports:
        - containerPort: 8081
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql+psycopg2://swapi:swapi_pass@swapi-db-service:5432/swapi_db"
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: swapi-backend-service
spec:
  selector:
    app: swapi
    tier: backend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
