sonar.projectKey=swapi-app
sonar.projectName=SWAPI App
sonar.projectVersion=1.0

sonar.sources=assignment-4/app
sonar.exclusions=assignment-4/app/tests/**,**/__pycache__/**,**/*.pyc

sonar.python.coverage.reportPaths=assignment-4/app/coverage.xml
sonar.coverage.exclusions=assignment-4/app/tests/**

sonar.sourceEncoding=UTF-8
